### ISSUE TITLE
uuid error

### ISSUE THREAD

**Issue by satyendrasingh8** [uuidjs/uuid#448] opened 2020-05-12 04:29 UTC
Uncaught TypeError: (0 , _uuid2.default) is not a function
  
in version uuid@8.0.0 (WHY gettig this error)

but
 it can be resolve using uuid@3.1.0

## To Reproduce

1. Install '...'
2. Run '....'
3. See error

## Runtime

- OS: [e.g. macOS, Linux]
- Runtime: [e.g. Node.js, Chrome, Safari, react-native, AWS Lambda]
- Runtime Version: [e.g. 14.2.0]

**Comment by satyendrasingh8** [comment] 2020-05-12 04:30
Uncaught TypeError: (0 , _uuid2.default) is not a function

in version uuid@8.0.0 (WHY gettig this error)

but
it can be resolve using uuid@3.1.0

**Comment by ctavan** [comment] 2020-05-12 06:49
Duplicate of #447, please add more information on how you are importing/requiring `uuid` there.

**Closed by ctavan** 2020-05-12 06:49 UTC

**Comment by ctavan** [comment] 2020-05-13 14:31
Please check our documentation: https://github.com/uuidjs/uuid#quickstart

The correct way of importing this library is (assuming you want random/v4 UUIDs):

```js
import { v4 as uuidv4 } from 'uuid';
uuidv4();
```

**Comment by satyendrasingh8** [comment] 2020-05-13 15:12
You only copy paste from google
But it support for version uuid@3.1.0

**Comment by satyendrasingh8** [comment] 2020-05-13 15:31
[redux-expensify.txt](https://github.com/uuidjs/uuid/files/4622964/redux-expensify.txt)

**Comment by ctavan** [comment] 2020-05-13 15:59
I'm not sure what you are trying to tell me. Usage of this library is well-documented in the project's readme: https://github.com/uuidjs/uuid#quickstart

Please simply import the library in the documented way.
