### ISSUE TITLE
ES6 import support?

### ISSUE THREAD

**Issue by Samstiles** [uuidjs/uuid#245] opened 2017-12-21 01:54 UTC
Hey y'all,

Thanks for your work on this lib. Any plans for ES6 import support in the near future? If it's something actively being worked on I'm gonna wait, otherwise I may look into possibly PRing?

EG

`import { uuidv1 } from 'node-uuid'`

**Comment by ZachMayer35** [comment] 2018-01-02 20:50
not quite what your example asks for, but you can already do this:

`import {v4 as uuidv4} from 'uuid';`

or just

`import {v4} from 'uuid';`

if you're not picky about the accessor.

**Comment by broofa** [comment] 2018-01-04 22:34
As [noted in the README](https://github.com/kelektiv/node-uuid#deprecated-api),  importing `uuid` is deprecated.  Instead, import `uuid/<version>`.   E.g. to import the v1 generator using ES6 notation:

`import uuidv1 from 'uuid/v1';`

(Note: I haven't tested this, but give it a try and report back here with the results.  I'll reopen if this is a legit issue.)

**Comment by Oliboy50** [comment] 2018-08-27 12:41
@broofa `import uuid from 'uuid/v4';` syntax does not work, at least in a Typescript v3 project running on Node v10.9.0

on the other hand, `import {v4 as uuid} from 'uuid';` works as expected

**Comment by broofa** [comment] 2018-11-03 15:17
Apologies for the late response on this.  I [still] consider this issue closed, but in light of the "reactions" the above comment has garnered, let me state my position on this...

> at least in a Typescript v3 project 

... which makes this a Typescript (or TS configuration) issue.  This module conforms with the documented CommonJS and ES6 behaviors.  You can use ES6 syntax either directly in the browser or via webpack w/out issue, so whatever the issue is here, it's specific to TS.

**Comment by Oliboy50** [comment] 2018-11-03 20:19
@broofa actually you're right, in my case this was only due to how `Typescript` is handling ES6 imports

so, just like many other JS libs like this one, it works this way using TS:

```ts
import * as uuid from "uuid/v4";

console.log(uuid());
```

here is a codesandbox to play with: https://codesandbox.io/s/5372omm68n

**Comment by jonathanstiansen** [comment] 2019-02-26 23:44
@Sampath-Lokuge that doesn't work in Typescript.

**Comment by Sampath-Lokuge** [comment] 2019-02-27 09:43
@jonathanstiansen What was the error? I have used above on Ionic / Typescript app and no issues.

**Comment by MartinX3** [comment] 2019-03-02 12:04
Typescript 3.2.4 in angular 7.2.7

Creating an object from this class
```
import { UUID } from 'uuid/v4';

export class entity {
  id: string;
  name: string;

  constructor() {
    this.id = UUID();
    this.name = '';
  }
}
```
results in
> ERROR TypeError: "Object(...) is not a function"

**Comment by vladshcherbin** [comment] 2019-04-26 01:10
Should be reopened and fixed.

[Rollup](https://github.com/rollup/rollup) is also giving error, with `import uuidv4 from 'uuid/v4'`. Plugins need to be used to fix it there and this's a single package I met which requires actions from developer to make imports work.

Current [index.js](https://github.com/kelektiv/node-uuid/blob/v3.3.2/index.js) with exports is a mess and should be changed to a correct one so we don't need to import from separate files. Package.json file also doesn't reflect needed files.

Es modules support would be also great since it's actually quite easy to add and maintain using modern tools.

@broofa if you are okay with this, PR's can be made to reflect this changes as this package clearly needs some fresh updates to it 😉

**Comment by broofa** [comment] 2019-04-26 17:45
> Current index.js with exports is a mess

Agreed.  Hence the deprecation warning about it going away.

FWIW, the problem with hanging all versions off the top-level `module` is that it it creates a dependency tree that causes packagers to pull in all 350-600 lines of code in this module, even in the very-common case where you only need the 30-50 lines required to implement `v4`.

> Rollup is also giving error

What's the Rollup team have to say about this?

**Comment by vladshcherbin** [comment] 2019-04-26 22:33
@broofa rollup team is pushing forward es modules, for a very long time. To get rid of such cjs errors, a plugin (rollup-plugin-commonjs) should be used there, but with top imports from `index.js` file it's not needed.

Top level exports from `index.js` file shouldn't be a problem because tree shaking is used to get only needed dependencies. Rollup and webpack both have it and should remove unused functions from bundle. So, if you only import v4 function, all other functions should be removed.

**Comment by broofa** [comment] 2019-04-27 13:20
tree-shaking only works on ES6 modules ([according to webpack](https://webpack.js.org/guides/tree-shaking/#conclusion)).

**Comment by vladshcherbin** [comment] 2019-04-27 13:29
@broofa yep, this is why I [am proposing](https://github.com/kelektiv/node-uuid/issues/245#issuecomment-486889893) to add es modules to this package.

Bundlers (webpack, rollup) will use es modules and tree shake unused exports while cjs users will have a separate cjs version. This is how a lot of modern packages work nowadays :)

**Comment by arjunyel** [comment] 2019-05-08 20:24
I recommend using pika pack, it will generate Deno, browser, and Node compatible versions https://next.pikapkg.com/blog/introducing-pika-pack/

**Comment by cannjeff** [comment] 2019-05-14 15:16
Any ETA on this?

**Comment by broofa** [comment] 2019-05-14 18:33
@cannjeff:   There's no ETA.  If your packager doesn't support ES6-style import of CommonJS modules like this one, then you need to take that up with the packager project.

**Comment by arjunyel** [comment] 2019-05-14 20:05
Would you accept a PR that created different distribution types?

**Comment by broofa** [comment] 2019-05-14 22:06
@arjunyel: Short answer? No, not at this time.

Longer answer: I know this is causing people pain, and I genuinely feel bad about not being responsive to that.  However, to the best of my knowledge this module complies with the CommonJS spec, which makes this an issue with how packagers do/does support CommonJS -> ES6 transpiling.  Adding extra complexity to this project to create packager-specific distributions (which are just going to get repackaged/transpiled a second time anyhow) is not something I'm interested in.

I'm open to continuing this conversation, but only to the extent you or others (or, ideally, the Rollup/Angular/Typescript teams) make a compelling argument for why this problem should be fixed here rather than in the packagers.  To date, I haven't seen that effort being made.

**Comment by thepassle** [comment] 2019-06-18 07:46
I feel like his may be relevant to the discussion here: https://jasonformat.com/enabling-modern-js-on-npm/ and will hopefully make you reconsider 😊

**Comment by quanganhtran** [comment] 2019-06-20 11:01
I came to this issue after going from https://www.pika.dev/search?q=uuid
> Package found! However, no "module" entrypoint was found in its package.json manifest. If possible, explore the site for a more web-friendly alternative.

I believe as patterns like this get adopted, ES module is going to be directly used in the browser instead of being repackaged or transpiled away.

**Comment by robrez** [comment] 2019-06-20 17:39
We've published a mirror of this repo which is bundled as ESM.

https://github.com/bundled-es-modules/uuid
https://www.npmjs.com/package/@bundled-es-modules/uuid

Cheers

**Comment by ctavan** [comment] 2020-02-17 22:59
Sorry for taking such a long time but we have finally released `uuid@7.0.0-beta.0` which features native ESModules-Support for the browser:

```
npm install uuid@7.0.0-beta.0
```

The [master branch README](https://github.com/uuidjs/uuid/blob/master/README.md) already reflects the API of v7.0.0.

It would be awesome to get feedback from you if this release works well for you.

**Comment by Oliboy50** [comment] 2020-02-18 08:56
To try your different uuid releases using Typescript, you can use this sandbox if you want: https://codesandbox.io/s/gallant-voice-iwy7z

(I personnally didn't try to use `uuid` without TS, so I don't know how to make sure your ESModule configuration works using vanilla JS)

anyway, both versions (`3.4.0` and `7.0.0-beta.0`) seem to work fine with Typescript using this syntax:

```ts
import uuid from "uuid/v4"
```

as long as you:
- add this dev dependency: `"@types/uuid": "3.4.7"`
- make sure `"esModuleInterop": true` is set in your `tsconfig` file

**Comment by ctavan** [comment] 2020-02-18 13:07
@Oliboy50 thanks for trying it out and posting the link to the sandbox!

I want to highlight that the new recommended way of importing is now:

```js
import { v4 as uuidv4 } from "uuid";

document.getElementById("app")!.innerHTML = `<h1>${uuidv4()}</h1>`;
```

I quickly tried it out with your sandbox and it seems to work as well! Can you confirm that?

**Comment by ctavan** [comment] 2020-02-18 13:18
Oh, and @Oliboy50 if I'm not totally mistaken you can drop ` "esModuleInterop": false` from your `tsconfig` if you use the new way of importing the library!

**Comment by ctavan** [comment] 2020-02-24 13:36
We have just released [`uuid@7.0.0`](https://github.com/uuidjs/uuid/blob/v7.0.0/CHANGELOG.md#700-2020-02-24) which now features native ES6 import support. Please feel free to open a new issue if you encounter any issues with the new version.

**Comment by dps910** [comment] 2020-03-14 12:40
I get a syntax error when importing uuid
`SyntaxError: The requested module 'uuid' does not provide an export named 'v4'`

**Comment by TrySound** [comment] 2020-03-14 13:07
@dps910 Which version do you see in your node_modules?

**Comment by dps910** [comment] 2020-03-14 13:12
> @dps910 Which version do you see in your node_modules?

version 7.0.2

**Comment by TrySound** [comment] 2020-03-14 13:16
Ah, it's node. Only bundlers esm is supported for now.
https://github.com/uuidjs/uuid/pull/402

Can you try this?
import uuid from 'uuid';
uuid.v4

**Comment by dps910** [comment] 2020-03-14 13:21
> Ah, it's node. Only bundlers esm is supported for now.
> #402
> 
> Can you try this?
> import uuid from 'uuid';
> uuid.v4

thanks, it works :smile:

**Comment by FloodGames** [comment] 2020-04-27 15:22
> Ah, it's node. Only bundlers esm is supported for now.
> #402
> 
> Can you try this?
> import uuid from 'uuid';
> uuid.v4

WARNING in ./src/server/object.js 204:14-18
    "export 'default' (imported as 'uuid') was not found in 'uuid'

Yes, it's the latest node trying to use 'import'

**Comment by ctavan** [comment] 2020-04-27 15:45
@FloodGames I'm not sure what you are trying to say.

Per [the docs](https://github.com/uuidjs/uuid#version-4-random) the recommended way of using `uuid` as an ES Module is:

```js
import { v4 as uuidv4 } from 'uuid';
uuidv4(); // ⇨ '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'
```

Does this not work for you?

**Comment by ctavan** [comment] 2020-04-27 15:51
Oh, I think I lost something in my previous answer. This does indeed currently not work in blank nodeNode.js.

Running Node.js 14.0.0 I can do the following:

```js
import uuid from 'uuid';
console.log(uuid.v4()); // -> 'b80a7443-e722-4877-be96-4f608304ca81'
```

**Closed** 2020-04-29 11:40 UTC

**Comment by ctavan** [comment] 2020-04-29 20:47
For everyone in this thread: we have just released `uuid@8.0.0` which comes with native ESM support for Node.js! Let us know if that works for you. [See CHANGELOG](https://github.com/uuidjs/uuid/blob/master/CHANGELOG.md#800-2020-04-29) for more info.

@FloodGames @dps910  this means that the way to go from now on is:

```javascript
import { v4 as uuidv4 } from 'uuid';
uuidv4();
```

**Comment by dps910** [comment] 2020-04-29 21:36
> For everyone in this thread: we have just released `uuid@8.0.0` which comes with native ESM support for Node.js! Let us know if that works for you. [See CHANGELOG](https://github.com/uuidjs/uuid/blob/master/CHANGELOG.md#800-2020-04-29) for more info.
> 
> @FloodGames @dps910  this means that the way to go from now on is:
> 
> ```javascript
> import { v4 as uuidv4 } from 'uuid';
> uuidv4();
> ```

Yes, it is working thank you :)

**Comment by Tzahile** [comment] 2020-05-14 13:51
Hi, I'm using jest to test my project.
Trying to test a file where I import uuid results with an error:
```
 ● Test suite failed to run

    SyntaxError: The requested module 'uuid' does not provide an export named 'v1'

          at async Promise.all (index 0)
      at jasmine2 (node_modules/jest-jasmine2/build/index.js:228:5)
```

I saw @dps910 comment and I guess it's something similar.
I'm using UUID@8, node@14 and Jest@26 (and it's freshly-supported esm modules implementation).

Jest command:
`node --experimental-vm-modules .\node_modules\jest\bin\jest.js`
The file that I'm testing imports uuid like you suggested:
```js
import { v1 as uuidv1 } from 'uuid';
uuidv1();
```

It fails only when I'm testing though.

**Comment by picozzimichele** [comment] 2020-06-02 09:18
Had the same issue, this worked in fixing the import:

Import correct version (v1-4)

`import {v4 as uuid} from "uuid"` 

use now the function

`uuid()`

**Comment by kryz81** [comment] 2020-06-06 10:05
This compiled to typescript doesn't work:

```
import { v4 } from 'uuid';
v4();
```

I had to downgrade to v7

**Comment by erinoggz** [comment] 2020-08-11 15:22
const { v4: uuidv4 } = require( 'uuid' );
console.log ( uuidv4( ) )

**Comment by gizm0bill** [comment] 2021-01-21 07:20
Angular compilation warning: ```application.service.ts depends on 'uuid'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies```

**Comment by crystalfp** [comment] 2022-01-19 12:50
Maybe this could be useful to someone.

In a Vue application I call uuid this way: `import { v4 as uuid } from "uuid"` and receive the following error:
```
./node_modules/uuid/index.js
Module build failed: Error: ENOENT: no such file or directory, open 'D:\AProject\node_modules\uuid\index.js'
```
To make it works I have to change the import to: `import { v4 as uuid } from "uuid/dist/esm-browser"`
Hope it helps
mario

**Comment by broofa** [comment] 2022-01-19 15:51
> `Module build failed: Error: ENOENT: no such file or directory, open 'D:\AProject\node_modules\uuid\index.js'`

@crystalfp: This package does not supply a top level index.js.  If you look at our package.json, you'll see that the `main` and `exports` sections all point to files within the `dist` directory.  You'll need to figure out why Vue (or tsc or whatever...) is thinks it's supposed to have one.

**Comment by broofa** [comment] 2022-01-19 15:56
Locking this conversation.  Anyone having issues with importing `uuid` should just file a new issue.
