### ISSUE TITLE
"Error: Native module not found" error when using uuidv4 in React Native app (non Expo)

### ISSUE THREAD

**Issue by jkw-statsig** [uuidjs/uuid#570] opened 2021-04-13 07:22 UTC
## Describe the bug

When I try to use uuidv4 in my vanilla react native (non-Expo) app, I'm getting "Error: Native module not found" error. I'm importing the two needed dependencies correctly as far as I can tell, and the same way worked for my Expo app:

```
import 'react-native-get-random-values';
import {v4 as uuidv4} from 'uuid';
...
// some where in my render() function
const myID = uuidv4(); // throws error
```

I've verified /node_modules has the two packages downloaded correctly too.

## How to reproduce

Basically what I described above - I'm using basically a blank RN app.

## Expected behavior

uuidv4() should work with `react-native-get-random-values` imported above it.

## Runtime

- OS: macOS
- Runtime: react-native (non-Expo)
- Runtime Version: 0.64.0

**Comment by LinusU** [comment] 2021-04-13 07:48
Is this on iOS? Did you ran `pod install`?

I tried this in a fresh react native app just the other day, so would appreciate any more information on how to reproduce this ☺️

**Comment by jkw-statsig** [comment] 2021-04-13 08:00
Yes I'm running it for iOS and with a fresh react native app too (so no new iOS code by me on top of the barebone main and AppDelegate files). I did run pod install, though I'm not sure if it did what it's supposed to do.

```
::> npx pod-install
Scanning for pods...
1.10.1
> pod install
Auto-linking React Native module for target `ReactNativeVanilla`: RNCAsyncStorage
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 50 dependencies from the Podfile and 41 total pods installed.
```

I'm quite new to vanilla react native so there is a chance that I didn't set up the project correctly? But all I did was creating the project with `npx react-native init my-app` and run `npx react-native run-ios` at project root.

**Comment by jkw-statsig** [comment] 2021-04-13 08:09
Hmm I think I know why this particular callsite is not working - I didn't add `react-native-get-random-values` in the app's package.json - that's my bad. However, my problem wasn't initially on the blank app itself, but rather on a node_module I'm trying to import into the app, which has a dependency on uuid and does import `react-native-get-random-values` properly. 

In that case, `npm-install` did pull down both packages into /node_modules, but pod install from my project root wouldn't do anything because `react-native-get-random-values` isn't a direct dependency on my app. Is this the problem? If so, is there any way for the package with uuid dependency to work for other react native apps as a SDK, without asking the other apps to take on `react-native-get-random-values` as a direct dependency?

**Comment by enricop89** [comment] 2021-06-24 09:53
@jkw-statsig I have your same problem. I am adding a library that uses `react-native-get-random-values` so my main app is not having `react-native-get-random-values` as a dependency. Did you find a way to overcome this problem?

**Comment by jkw-statsig** [comment] 2021-06-24 16:52
@enricop89 I ended up asking the users of my library to add it as a direct dependency on their app/project. Did not find any other workaround.

**Comment by ctavan** [comment] 2021-06-24 20:51
I think the fact that a manual `npx pod-install` is currently necessary in order to install `react-native-get-random-values` is something that cannot be fixed in `uuid` but would have to be approached in https://github.com/LinusU/react-native-get-random-values, so feel free to raise an issue over there.

Until then I think the best bet is to make `react-native-get-random-values` a `peerDependency` of your library and document the necessary steps to install it.

Maybe one more idea: Have you tried adding `react-native-get-random-values` as a dependency to your library and the necessary manual install steps in a [`postinstall`](https://docs.npmjs.com/cli/v7/using-npm/scripts#npm-install) hook?

**Comment by jaaywags** [comment] 2021-07-25 14:31
This is probably not your issue, but thought I would throw it out there anyway. Did you install the types?
`npm i --save-dev @types/uuid`

**Comment by h4rdrew** [comment] 2021-12-07 20:29
> This is probably not your issue, but thought I would throw it out there anyway. Did you install the types? `npm i --save-dev @types/uuid`

thanks, it worked for me

**Comment by LinusU** [comment] 2021-12-08 10:20
> [...] make `react-native-get-random-values` a `peerDependency` of your library and document the necessary steps to install it.

This is what I would recommend as well 👍 

I think we can close this one now since a workaround have been found, there doesn't seem to be anything we can change in `uuid`, and there hasn't been any recent activity...

**Closed by LinusU** 2021-12-08 10:20 UTC

**Comment by MerryCello** [comment] 2022-10-24 19:01
> I think the fact that a manual `npx pod-install` is currently necessary in order to install `react-native-get-random-values` is something that cannot be fixed in `uuid` but would have to be approached in https://github.com/LinusU/react-native-get-random-values, so feel free to raise an issue over there.
> 
> Until then I think the best bet is to make `react-native-get-random-values` a `peerDependency` of your library and document the necessary steps to install it.
> 
> Maybe one more idea: Have you tried adding `react-native-get-random-values` as a dependency to your library and the necessary manual install steps in a [`postinstall`](https://docs.npmjs.com/cli/v7/using-npm/scripts#npm-install) hook?

This worked for me, thank you!
