### ISSUE TITLE
No valid exports for node_modules/uuid ( v8.0.0 )

### ISSUE THREAD

**Issue by svarlitskiy** [uuidjs/uuid#436] opened 2020-05-05 23:36 UTC
## Describe the bug

```js
Welcome to Node.js v13.5.0.
Type ".help" for more information.
> uuid = require('uuid')
Uncaught:
Error: No valid exports main found for 'node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  code: 'MODULE_NOT_FOUND'
}
```

## To Reproduce

1. Install Nodejs v13.5.0
2. npm install uuid@8.0.0
3. Launch node
4. require `const uuid = require('uuid');`

## Runtime

- OS: Linux 4.19.0-8-amd64 Debian x86_64 GNU/Linux
- Nodejs v13.5.0
- npm v6.14.4
- uuid v8.0.0

**Comment by broofa** [comment] 2020-05-06 02:39
Duplicate of #428

**Closed by broofa** 2020-05-06 02:39 UTC
