### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by ali-heidari** [uuidjs/uuid#488] opened 2020-07-22 10:53 UTC
## Describe the bug

It seems there is a problem with exporting different versions inside of uuid. My project is using uuidv4 which is using uuid.

## To Reproduce

1. Install 'uuidv4'
2. Run project (commonJs style)
3. See error

## Expected behavior

Expected to run without problem.

## Runtime

- OS: Win10
- Runtime: Node.js
- Runtime Version: 14.3.0

## Additional context

You can see the error here:

```js
...\node_modules\uuidv4\node_modules\uuid\dist\esm-browser\index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
```

**Comment by TrySound** [comment] 2020-07-22 11:12
This point is not clear. Is it node project or some bundler, which bundler?
> Run project (commonJs style)

**Comment by ali-heidari** [comment] 2020-07-23 04:00
It is node project... I guess it happens because of my node written in commonJs and uuid is es6!

**Comment by TrySound** [comment] 2020-07-23 06:56
Nope. UUID is distributed as commonjs by default.
https://unpkg.com/browse/uuid@8.2.0/dist/index.js

How do you import uuid? And provide please minimal reproduction.

**Comment by ali-heidari** [comment] 2020-07-23 07:38
But my console shows an error 

```js
node_modules\uuidv4\node_modules\uuid\dist\esm-browser\index.js:1
    export { default as v1 } from './v1.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'
        at compileFunction (<anonymous>)
        at wrapSafe (internal/modules/cjs/loader.js:1116:16)
        at Module._compile (internal/modules/cjs/loader.js:1164:27)
```

which pointed to this file:

```js
export { default as v1 } from './v1.js';
export { default as v3 } from './v3.js';
export { default as v4 } from './v4.js';
export { default as v5 } from './v5.js';
```

What am i missing here?

**Comment by TrySound** [comment] 2020-07-23 07:50
Show how do you import uuid, give us a reproduction.

**Comment by ali-heidari** [comment] 2020-07-23 07:57
This is how i import:
```js
const { uuid } = require('uuidv4');
```

**Comment by TrySound** [comment] 2020-07-23 08:08
This package?
https://www.npmjs.com/package/uuidv4

**Comment by TrySound** [comment] 2020-07-23 08:08
The wrong one. Please read documentation.

**Comment by TrySound** [comment] 2020-07-23 08:12
I see. This package is the dependency of your one. Could you switch to using `uuid` package directly?

**Comment by ctavan** [comment] 2020-07-27 19:11
Closing since this seems to be related to a reverse dependency of this package. Please open a bug report in the appropriate issue tracker if the problem persists: https://github.com/thenativeweb/uuidv4/

**Closed by ctavan** 2020-07-27 19:11 UTC

**Comment by riccardoNovaglia** [comment] 2020-08-05 06:44
Hey folks, I think this still might be an issue, getting exactly the same problem, importing uuid directly.

Made a repo [here](https://github.com/riccardoNovaglia/uuid-issue) to show the problem.

Hope it helps

**Comment by ctavan** [comment] 2020-08-05 07:13
@riccardoNovaglia your node version has incomplete support for the `package.exports` feature. It's also not actively supported by Node.js anymore, see https://nodejs.org/en/about/releases/

Please upgrade to Node.js `v14` if you want to use ESM or downgrade to `v12` if you want to use CommonJS.

**Comment by riccardoNovaglia** [comment] 2020-08-05 07:30
@ctavan absolutely right. Can confirm it works with both v12 and v14. Thanks for the help!

**Comment by asitbiswas** [comment] 2020-09-26 11:42
update your node. i had the same problem using node 13.3.0 and uuid 8.3.0.

then i upgraded to node 14.12.0 and it worked

**Comment by RatonBiswas** [comment] 2020-09-27 16:25
const { v4 : uuidv4 } = require('uuid');

export { default as v1 } from './v1.js';
^^^^^^
SyntaxError: Unexpected token 'export'

How can I solve this?

**Comment by TrySound** [comment] 2020-09-27 16:36
@RatonBiswas Why do you mix commonjs and es modules? `uuid` supports both. And what is your environment? We cannot help without additional information.

**Comment by RatonBiswas** [comment] 2020-09-28 07:10
> update your node. i had the same problem using node 13.3.0 and uuid 8.3.0.
> 
> then i upgraded to node 14.12.0 and it worked

yes, you are right.

**Comment by fatihyenidunya** [comment] 2020-10-22 10:40
if it is still not running after updated node, try update  uuid **npm install uuid**

**Comment by guillefix** [comment] 2020-11-13 05:18
I still have this issue

**Comment by ctavan** [comment] 2020-11-13 09:26
@guillefix please see: https://github.com/uuidjs/uuid/issues/488#issuecomment-664585063
