### ISSUE TITLE
UUID Generation in Non-Browser Context (eg. NativeScript)

### ISSUE THREAD

**Issue by BallisticPain** [uuidjs/uuid#556] opened 2021-02-02 00:31 UTC
## Is your feature request related to a problem? Please describe.

When I import and use `uuid` in a NativeScript application I receive an error `cannot get 'browser' of undefined`. Initially I didn't realize this was related to the UUID library. But the moment I removed attempted `v4()` generation the application compiled without any errors.

## Describe the solution you'd like

I would love to use `uuid` as per the documentation even when in a mobile device situation such as NativeScript. I saw the ReactNative support and was hopeful. However, upon a quick peek it didn't seem to be a user friendly solution and I didn't want to attempt to port it.

## Describe alternatives you've considered

I've looked at `guid-typescript`, however, it is unmaintained even though it's downloaded 67k+ times per week according to NPM.

Another alternative that I have considered is to write a NativeScript plugin that uses Android / iOS functionality to generate the UUIDs but felt that would only benefit a smaller community.

## Additional context

I imagine if the solution were implemented very well it could cross all the non-browser contexts. I'm not certain how feasible this is, but I hope this is the right place to ask.

Thanks for this UUID library!

**Comment by broofa** [comment] 2021-02-02 01:40
Is this related to #551 and #469?  (`mainFields` order in webpack)

@BallisticPain I believe this is the first issue we've had related to NativeScript, and I don't know that any of us maintainers have worked with that toolchain before.  A [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/minimal-reproducible-example) example, _⟪cough⟫ as requested in the bug report template ⟪cough⟫_ would be helpful.  E.g. a small repo that we can clone, with instructions for building and reproducing the error.

**Comment by broofa** [comment] 2021-02-02 01:46
Duplicate of #314.

@BallisticPain - A [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/minimal-reproducible-example) example, _⟪cough⟫ as requested in the bug report template ⟪cough⟫_ would be helpful.  E.g. a small repo that we can clone, with instructions for building and reproducing the error.

**Comment by ctavan** [comment] 2021-02-06 13:03
@BallisticPain please check my comment in https://github.com/uuidjs/uuid/issues/314#issuecomment-737761009

If reordering `resolve.mainFields` doesn't work for you, feel free to reopen this issue and proved an example as outlined by @broofa above.

**Closed by ctavan** 2021-02-06 13:03 UTC
