### ISSUE TITLE
v7.0.1 crashes React Native

### ISSUE THREAD

**Issue by ethanneff** [uuidjs/uuid#389] opened 2020-02-28 16:08 UTC
## Describe the bug

A lot of breaking changes in v7.0.1 uuid

v3.4.0|v7.0.1|v7.0.1 + react-native-get-random-values
---|---|---
works|<img width="464" alt="Screen Shot 2020-02-28 at 8 04 02 AM" src="https://user-images.githubusercontent.com/2933593/75564532-29255100-5a01-11ea-8ed8-e5a10262683b.png">|<img width="464" alt="Screen Shot 2020-02-28 at 7 52 39 AM" src="https://user-images.githubusercontent.com/2933593/75564538-2aef1480-5a01-11ea-847b-0fed71359b9e.png">

## To Reproduce

https://reactnative.dev/docs/getting-started
https://github.com/uuidjs/uuid
https://github.com/LinusU/react-native-get-random-values

## Expected behavior

Not crashing like v3.4.0

**Comment by ctavan** [comment] 2020-02-28 16:18
Duplicate of #375

**Comment by ctavan** [comment] 2020-02-28 16:40
OK, looks like this issue is a bit more specific than #375, see https://github.com/uuidjs/uuid/pull/390#issuecomment-592594777

Reopening until we have a working react native example.

**Comment by LinusU** [comment] 2020-03-02 07:47
@ethanneff is this with Expo? or are you using vanilla React Native?

If you are using Expo, you currently have to wait for https://github.com/expo/expo/issues/7209 to be fixed.

If you are using vanilla React Native it seems like your auto-linking have failed. I'm no expert here, but I _think_ that running `pod install` in the `ios` directory should fix it:

```
cd ios
pod install
cd ..
react-native run-ios
```

**Comment by ctavan** [comment] 2020-03-02 13:24
@ethanneff I'm pretty sure you are running into the same issue that I ran into in #390. Please check out that PR to see if it fixes your issue.

**Comment by ethanneff** [comment] 2020-03-02 15:29
You are correct. 

```
$ pod install --repo-update
Installing react-native-get-random-values (1.2.0)
```

**Closed** 2020-03-02 15:31 UTC

**Comment by LinusU** [comment] 2020-03-02 18:14
I've also added the `pod install` step to the readme for react-native-get-random-values 👍
