### ISSUE TITLE
Issue in the import statement

### ISSUE THREAD

**Issue by sekharpulavarthi** [uuidjs/uuid#743] opened 2024-02-06 10:47 UTC
### Before you begin...

- [X] I have searched the existing issues
- [X] I am not using version 13.x of node  (if so, please upgrade)

### Description of the problem

As per the **wrapper.mjs** 

There is no export statement with the name uuidv4, so when we write the below import statement, we are getting the error as v4 is not defined, it is worked when we directly import the v4 from uuid package

//NotWorking:
**import { v4 as uuidv4 } from 'uuid';**

//Working:
**import { v4 } from 'uuid';**

import uuid from './dist/index.js';
export const v1 = uuid.v1;
export const v3 = uuid.v3;
export const v4 = uuid.v4;
export const v5 = uuid.v5;
export const NIL = uuid.NIL;
export const version = uuid.version;
export const validate = uuid.validate;
export const stringify = uuid.stringify;
export const parse = uuid.parse;
<img width="542" alt="Screenshot 2024-02-06 at 4 14 19 PM" src="https://github.com/uuidjs/uuid/assets/54624167/a72b28d1-0bb3-47ea-b74c-27ee169eaf88">

So, as per my understanding, need to update the documentation or wrapper.mjs file

**Comment by broofa** [comment] 2024-02-06 15:31
Duplicate of https://github.com/uuidjs/uuid/issues/651#issuecomment-1225897883

**Closed by broofa** 2024-02-06 15:31 UTC
Labels: bug
