### ISSUE TITLE
[BUG] Only named exports may use 'export type'.

### ISSUE THREAD

**Issue by lwandokasuba** [uuidjs/uuid#850] opened 2024-12-29 20:00 UTC
### Before you begin...

- [X] I have searched the existing issues
- [X] I am not using version 13.x of node  (if so, please upgrade)

### Description of the problem

I'm trying to use uuid for a Firebase project, but each time I try to run it I get this error during the build. Kindly advise if I'm doing something wrong or if it's something out of my control.

<img width="488" alt="Screenshot 2024-12-29 at 9 49 25 PM" src="https://github.com/user-attachments/assets/c556a731-a36b-4f8f-9751-0207ac8eebce" />

### Recipe for reproducing

```bash
Running `pnpm run serve`
```

### Additional information

A copy of my tsconfig.json

```
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017"
  },
  "compileOnSave": true,
  "include": [
    "src"
  ]
}
```

### Environment

``` 
System:
    OS: macOS 12.7.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 421.03 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.20.5 - ~/.nvm/versions/node/v18.20.5/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v18.20.5/bin/npm
    pnpm: 9.15.2 - ~/.nvm/versions/node/v20.18.1/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.205
    Safari: 17.6
  npmPackages:
    @types/express: ^5.0.0 => 5.0.0 
    @typescript-eslint/eslint-plugin: ^5.12.0 => 5.62.0 
    @typescript-eslint/parser: ^5.12.0 => 5.62.0 
    eslint: ^8.9.0 => 8.57.1 
    eslint-config-google: ^0.14.0 => 0.14.0 
    eslint-plugin-import: ^2.25.4 => 2.31.0 
    express: ^4.21.2 => 4.21.2 
    firebase-admin: ^12.1.0 => 12.7.0 
    firebase-functions: ^5.0.0 => 5.1.1 
    firebase-functions-test: ^3.1.0 => 3.4.0 
    graphql: ^16.10.0 => 16.10.0 
    graphql-http: ^1.22.3 => 1.22.3 
    typescript: ^4.9.0 => 4.9.5 
    unique-names-generator: ^4.7.1 => 4.7.1 
    uuid: ^11.0.3 => 11.0.3 
```

**Comment by broofa** [comment] 2024-12-30 19:49
Duplicate of #837.  Updating to `typescript@5` should fix this issue.

**Closed by broofa** 2024-12-30 19:49 UTC
Labels: bug
